server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  redis:
    database: 0         #redis数据库索引默认为0
    host: 127.0.0.1     #redis服务器地址
    port: 6379          #redis服务器端口号
    password:           #redis服务器连接密码默认为空
    jedis:
      pool:
        max-active: 200 #redis连接池最大连接数，负数代表没有限制
        max-wait: -1    #连接池最大阻塞等待时间，负数代表没有限制
        max-idle: 10    #连接池最大空闲连接
        min-idle: 0     #连接池最小空闲连接
    timeout: 1000       #连接超时时间

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization:
#      write-dates-timestamps: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  config-location:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    #逻辑删除配置
    db-config:
      #删除后
      logic-delete-value: 0
      #删除前
      logic-not-delete-value: 1
